"use client";
import { Camera, LoaderCircle } from "lucide-react";
import { useRef, useState } from "react";
import { createSupabaseClient } from "@/lib/supabase/client";

export function AvatarUploadClient({ userId, initialUrl, initials }: { userId: string | null; initialUrl?: string | null; initials: string }) {
  const inputRef = useRef<HTMLInputElement>(null); const [url, setUrl] = useState(initialUrl ?? null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function upload(file?: File) { if (!file || !userId) return; if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) { setMessage("Нужна фотография JPG, PNG или WebP до 5 МБ."); return; } const supabase = createSupabaseClient(); if (!supabase) { setMessage("Подключение профиля недоступно."); return; } setBusy(true); setMessage(null); const ext = file.name.split(".").pop()?.toLowerCase() || "jpg"; const path = `${userId}/avatar-${Date.now()}.${ext}`; const { error: uploadError } = await supabase.storage.from("profile-avatars").upload(path, file, { upsert: true, contentType: file.type }); if (uploadError) { setMessage(`Не удалось загрузить: ${uploadError.message}`); setBusy(false); return; } const publicUrl = supabase.storage.from("profile-avatars").getPublicUrl(path).data.publicUrl; const { error } = await supabase.from("profiles").update({ avatar_url: publicUrl }).eq("id", userId); setBusy(false); if (error) { setMessage(`Не удалось сохранить: ${error.message}`); return; } setUrl(publicUrl); setMessage("Фотография профиля обновлена."); }
  return <div className="flex items-center gap-3"><button type="button" onClick={() => inputRef.current?.click()} disabled={!userId || busy} className="group relative h-20 w-20 shrink-0 overflow-hidden rounded-3xl border border-white/15 bg-[#111b3c] disabled:opacity-50">{url ? <img src={url} alt="Фотография профиля" className="h-full w-full object-cover" /> : <span className="grid h-full w-full place-items-center text-lg font-semibold">{initials}</span>}<span className="absolute inset-x-0 bottom-0 grid h-7 place-items-center bg-black/60 text-white transition group-hover:h-9">{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Camera className="h-4 w-4" />}</span></button><div><button type="button" onClick={() => inputRef.current?.click()} disabled={!userId || busy} className="text-sm font-semibold text-blue-100 hover:text-white disabled:opacity-50">Загрузить свою фотографию</button><p className="ui-note mt-1 text-xs">JPG, PNG или WebP · до 5 МБ</p>{message ? <p className="mt-1 text-xs text-amber-100">{message}</p> : null}</div><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => void upload(event.target.files?.[0])} /></div>;
}
